spring:
  application:
    name: account-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/transactions

server:
  port: 8082

logging:
  file:
    name: logs/transaction-service.log
  level:
    root: INFO
